apiVersion: batch/v1
kind: Job
metadata:
  name: med-20sec
spec:
  template:
    spec:
      containers:
        - name: med-20sec
          image: registry.access.redhat.com/ubi8/ubi:latest
          command: ['sh', '-c', 'echo The app is running! && sleep 20']
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      restartPolicy: Never
      priorityClassName: medium-priority
  backoffLimit: 4


  