apiVersion: v1
kind: Pod
metadata:
  name: high-20sec
spec:
  containers:
    - name: high-20sec
      image: registry.access.redhat.com/ubi8/ubi:latest
      command: ['sh', '-c', 'echo The app is running! && sleep 20']
      resources:
        requests:
          memory: "45Gi"
          cpu: "50m"
  restartPolicy: Never
  priorityClassName: high-priority


  