apiVersion: v1
kind: Pod
metadata:
  name: low-20sec
spec:
  containers:
    - name: low-20sec
      image: registry.access.redhat.com/ubi8/ubi:latest
      command: ['sh', '-c', 'echo The app is running! && sleep 20']
      resources:
        requests:
          memory: "45Gi"
          cpu: "50m"
  restartPolicy: Never
  priorityClassName: low-priority


  